"""org contacts

Revision ID: 06eb5c997ac1
Revises: ec9857ce7af1
Create Date: 2026-06-05 11:59:39.131413

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06eb5c997ac1'
down_revision: str | None = 'ec9857ce7af1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['org.client_companies.id'], name=op.f('fk_contacts_client_company_id_client_companies'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    schema='org'
    )
    op.create_index(op.f('ix_org_contacts_client_company_id'), 'contacts', ['client_company_id'], unique=False, schema='org')
    op.create_index(op.f('ix_org_contacts_email'), 'contacts', ['email'], unique=False, schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_contacts_email'), table_name='contacts', schema='org')
    op.drop_index(op.f('ix_org_contacts_client_company_id'), table_name='contacts', schema='org')
    op.drop_table('contacts', schema='org')
    # ### end Alembic commands ###
