"""add storage files and recruitment candidates

Revision ID: 070a95505ebb
Revises: ed81c547b139
Create Date: 2026-06-05 13:56:56.150063

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '070a95505ebb'
down_revision: str | None = 'ed81c547b139'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector type for candidates.cv_embedding — extension must exist first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_key', sa.String(length=1000), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('stored_key', name=op.f('uq_files_stored_key')),
    schema='storage'
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('avatar_file_id', sa.Integer(), nullable=True),
    sa.Column('education_level_id', sa.Integer(), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('is_studying', sa.Boolean(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('cv_file_id', sa.Integer(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cv_embedding', Vector(dim=1536), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['storage.files.id'], name=op.f('fk_candidates_avatar_file_id_files'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['career_id'], ['org.parameters.id'], name=op.f('fk_candidates_career_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['city_id'], ['org.parameters.id'], name=op.f('fk_candidates_city_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['cv_file_id'], ['storage.files.id'], name=op.f('fk_candidates_cv_file_id_files'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['education_level_id'], ['org.parameters.id'], name=op.f('fk_candidates_education_level_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['province_id'], ['org.parameters.id'], name=op.f('fk_candidates_province_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_candidates_user_id_users'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('cedula', name=op.f('uq_candidates_cedula')),
    sa.UniqueConstraint('user_id', name=op.f('uq_candidates_user_id')),
    schema='recruitment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates', schema='recruitment')
    op.drop_table('files', schema='storage')
    # ### end Alembic commands ###
