"""add_comms_notifications_and_email_logs

Revision ID: 45d7866d3a23
Revises: 612423b7cad0
Create Date: 2026-06-05 18:42:35.381166

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d7866d3a23'
down_revision: str | None = '612423b7cad0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['org.parameters.id'], name=op.f('fk_email_logs_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs')),
    schema='comms'
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['org.parameters.id'], name=op.f('fk_notifications_channel_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['auth.users.id'], name=op.f('fk_notifications_recipient_id_users'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='comms'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications', schema='comms')
    op.drop_table('email_logs', schema='comms')
    # ### end Alembic commands ###
