"""add_talent_pool

Revision ID: 612423b7cad0
Revises: d3375501bac0
Create Date: 2026-06-05 18:38:11.321182

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612423b7cad0'
down_revision: str | None = 'd3375501bac0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_pool',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_vacancy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], name=op.f('fk_talent_pool_candidate_id_candidates'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['source_vacancy_id'], ['recruitment.vacancies.id'], name=op.f('fk_talent_pool_source_vacancy_id_vacancies'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent_pool')),
    schema='talent'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent_pool', schema='talent')
    # ### end Alembic commands ###
