"""org processes

Revision ID: 78cf70dd4956
Revises: 06eb5c997ac1
Create Date: 2026-06-05 12:04:31.251062

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cf70dd4956'
down_revision: str | None = '06eb5c997ac1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['org.client_companies.id'], name=op.f('fk_processes_client_company_id_client_companies'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org.departments.id'], name=op.f('fk_processes_department_id_departments'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes')),
    sa.UniqueConstraint('client_company_id', 'department_id', 'name', name='uq_processes_client_company_id_department_id_name'),
    schema='org'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes', schema='org')
    # ### end Alembic commands ###
