"""org profile templates and items

Revision ID: b15810ae792d
Revises: ff6145669f58
Create Date: 2026-06-05 12:14:52.673908

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15810ae792d'
down_revision: str | None = 'ff6145669f58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_templates',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['org.client_companies.id'], name=op.f('fk_profile_templates_client_company_id_client_companies'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org.departments.id'], name=op.f('fk_profile_templates_department_id_departments'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_templates')),
    schema='org'
    )
    op.create_table('profile_template_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['org.parameters.id'], name=op.f('fk_profile_template_items_category_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['template_id'], ['org.profile_templates.id'], name=op.f('fk_profile_template_items_template_id_profile_templates'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_template_items')),
    schema='org'
    )
    op.create_index(op.f('ix_org_profile_template_items_template_id'), 'profile_template_items', ['template_id'], unique=False, schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_profile_template_items_template_id'), table_name='profile_template_items', schema='org')
    op.drop_table('profile_template_items', schema='org')
    op.drop_table('profile_templates', schema='org')
    # ### end Alembic commands ###
