"""add recruitment applications documents notes

Revision ID: c8b076a3114c
Revises: 070a95505ebb
Create Date: 2026-06-05 15:02:09.798374

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b076a3114c'
down_revision: str | None = '070a95505ebb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('current_status_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_summary', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruitment.candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['current_stage_id'], ['org.process_stages.id'], name=op.f('fk_applications_current_stage_id_process_stages'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['current_status_id'], ['org.parameters.id'], name=op.f('fk_applications_current_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['status_id'], ['org.parameters.id'], name=op.f('fk_applications_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['recruitment.vacancies.id'], name=op.f('fk_applications_vacancy_id_vacancies'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('vacancy_id', 'candidate_id', name='uq_applications_vacancy_id_candidate_id'),
    schema='recruitment'
    )
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['recruitment.applications.id'], name=op.f('fk_application_documents_application_id_applications'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['file_id'], ['storage.files.id'], name=op.f('fk_application_documents_file_id_files'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['status_id'], ['org.parameters.id'], name=op.f('fk_application_documents_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_documents')),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_application_documents_application_id'), 'application_documents', ['application_id'], unique=False, schema='recruitment')
    op.create_table('application_notes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['recruitment.applications.id'], name=op.f('fk_application_notes_application_id_applications'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_notes')),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_application_notes_application_id'), 'application_notes', ['application_id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_application_notes_application_id'), table_name='application_notes', schema='recruitment')
    op.drop_table('application_notes', schema='recruitment')
    op.drop_index(op.f('ix_recruitment_application_documents_application_id'), table_name='application_documents', schema='recruitment')
    op.drop_table('application_documents', schema='recruitment')
    op.drop_table('applications', schema='recruitment')
    # ### end Alembic commands ###
