"""add recruitment interviews and availability

Revision ID: d3375501bac0
Revises: c8b076a3114c
Create Date: 2026-06-05 15:14:55.914010

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3375501bac0'
down_revision: str | None = 'c8b076a3114c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewer_availability',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_interviewer_availability_user_id_users'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewer_availability')),
    schema='recruitment'
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('process_stage_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_email', sa.String(length=255), nullable=True),
    sa.Column('offered_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slot_selection_token', sa.String(length=64), nullable=True),
    sa.Column('teams_meeting_url', sa.String(length=500), nullable=True),
    sa.Column('teams_meeting_id', sa.String(length=200), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_by_id', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['recruitment.applications.id'], name=op.f('fk_interviews_application_id_applications'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['interviewer_id'], ['auth.users.id'], name=op.f('fk_interviews_interviewer_id_users'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['process_stage_id'], ['org.process_stages.id'], name=op.f('fk_interviews_process_stage_id_process_stages'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['org.parameters.id'], name=op.f('fk_interviews_scheduled_by_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['status_id'], ['org.parameters.id'], name=op.f('fk_interviews_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews')),
    schema='recruitment'
    )
    op.create_index(op.f('ix_recruitment_interviews_application_id'), 'interviews', ['application_id'], unique=False, schema='recruitment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_interviews_application_id'), table_name='interviews', schema='recruitment')
    op.drop_table('interviews', schema='recruitment')
    op.drop_table('interviewer_availability', schema='recruitment')
    # ### end Alembic commands ###
