"""add recruitment vacancies

Revision ID: ed81c547b139
Revises: 82512bea6748
Create Date: 2026-06-05 13:47:35.767896

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed81c547b139'
down_revision: str | None = '82512bea6748'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('vacancy_name_id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('work_mode_id', sa.Integer(), nullable=False),
    sa.Column('profile_template_id', sa.Integer(), nullable=True),
    sa.Column('profile_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_level_id', sa.Integer(), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('work_schedule', sa.String(length=100), nullable=True),
    sa.Column('project_duration_years', sa.Integer(), nullable=False),
    sa.Column('project_duration_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['org.parameters.id'], name=op.f('fk_vacancies_career_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['city_id'], ['org.parameters.id'], name=op.f('fk_vacancies_city_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['org.client_companies.id'], name=op.f('fk_vacancies_client_company_id_client_companies'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['org.contacts.id'], name=op.f('fk_vacancies_contact_id_contacts'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org.departments.id'], name=op.f('fk_vacancies_department_id_departments'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['process_id'], ['org.processes.id'], name=op.f('fk_vacancies_process_id_processes'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['profile_template_id'], ['org.profile_templates.id'], name=op.f('fk_vacancies_profile_template_id_profile_templates'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['resource_level_id'], ['org.parameters.id'], name=op.f('fk_vacancies_resource_level_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['status_id'], ['org.parameters.id'], name=op.f('fk_vacancies_status_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['vacancy_name_id'], ['org.parameters.id'], name=op.f('fk_vacancies_vacancy_name_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['work_mode_id'], ['org.parameters.id'], name=op.f('fk_vacancies_work_mode_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies')),
    schema='recruitment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies', schema='recruitment')
    # ### end Alembic commands ###
