"""org process_stages

Revision ID: ff6145669f58
Revises: 78cf70dd4956
Create Date: 2026-06-05 12:11:00.854506

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6145669f58'
down_revision: str | None = '78cf70dd4956'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_stages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_final_positive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ip_created', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ip_updated', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['org.processes.id'], name=op.f('fk_process_stages_process_id_processes'), initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['org.parameters.id'], name=op.f('fk_process_stages_stage_id_parameters'), initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_stages')),
    sa.UniqueConstraint('process_id', 'order', name='uq_process_stages_process_id_order'),
    sa.UniqueConstraint('process_id', 'stage_id', name='uq_process_stages_process_id_stage_id'),
    schema='org'
    )
    op.create_index(op.f('ix_org_process_stages_process_id'), 'process_stages', ['process_id'], unique=False, schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_process_stages_process_id'), table_name='process_stages', schema='org')
    op.drop_table('process_stages', schema='org')
    # ### end Alembic commands ###
