"""Transient CV-to-company-profile conversion for the staff utility screen."""

from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.ai.application.cv_parse_service import parse_cv_bytes
from app.modules.ai.application.cv_prefill_service import prefill_from_bytes
from app.modules.ai.application.word_generator_service import build_profile_word_from_data
from app.modules.org.infrastructure.models import Parameter


async def convert_cv(pdf_bytes: bytes, session: AsyncSession) -> tuple[dict[str, Any], bytes]:
    """Analyze a PDF, build the corporate Word, and return a transient preview.

    No candidate, upload, AI parse job, or generated document is persisted. The
    caller receives the preview data and the generated bytes for immediate use.
    """
    personal = await prefill_from_bytes(pdf_bytes, session)
    parsed = await parse_cv_bytes(pdf_bytes) or {
        "experience": [], "projects": [], "skills": [], "tools": [],
        "soft_skills": [], "certifications": [],
    }

    ids = {
        key: personal.get(key)
        for key in ("cityId", "titleId", "universityId")
        if personal.get(key) is not None
    }
    names: dict[str, str] = {}
    if ids:
        rows = (
            await session.execute(
                select(Parameter).where(Parameter.id.in_(ids.values()))
            )
        ).scalars().all()
        by_id = {row.id: row.name for row in rows}
        names = {key: by_id.get(value, "") for key, value in ids.items()}

    profile = {
        "full_name": " ".join(filter(None, [personal.get("firstName"), personal.get("lastName")])),
        "position": "",
        "title": names.get("titleId", ""),
        "university": names.get("universityId", ""),
        "location": names.get("cityId", ""),
        "email": personal.get("email") or "",
        "id_number": personal.get("idNumber") or "",
        "phone": personal.get("phone") or "",
        "home_address": personal.get("homeAddress") or "",
    }
    document = build_profile_word_from_data(profile, parsed)
    warnings = []
    if not parsed.get("experience"):
        warnings.append("No se identificó experiencia laboral; revisa el PDF antes de descargar.")
    if not parsed.get("certifications"):
        warnings.append("No se identificaron cursos o certificaciones.")
    preview = {**personal, "catalogNames": names, "parsedData": parsed, "warnings": warnings}
    return preview, document
